// =============================================================================
// Auto-generated by wca_lut_edge.fpga.lut6_burn — DO NOT EDIT BY HAND
// Software reference only — NO board synthesis / place-and-route claimed.
//
// Source truth-table: format=wca_lut_edge.truth_table.v1
//   n_bits=4  allow_mask=0x557F (21887)  rows=16
//   source=difflogic  gate_backend=difflogic_python_trained:bitmask
//
// LUT-6 packing:
//   4-input single-output Boolean → 1× LUT6 equivalent(s). Fits one LUT6 with 2 spare input(s) tied to 0 in fabric. 5–6 bit: still 1× LUT6. 7-bit: 2×; 8-bit: 4× (INIT capacity).
//   spare_inputs_tied=2
//   estimates_by_n_bits={'1': 1, '2': 1, '3': 1, '4': 1, '5': 1, '6': 1, '7': 2, '8': 4}
//
// Hot path after train/export: pure combinational allow bit — no DiffLogic/DWN FP.
// =============================================================================
module wca_allow_lut (
  input  wire [3:0] bits,
  output wire              allow
);
  // Combinational LUT. For n_bits<=6 this maps to one fabric LUT6
  // (unused inputs tied to 1'b0). rom_style hint is advisory for tools.
  (* rom_style = "distributed" *)
  reg allow_r;
  assign allow = allow_r;

  always @(*) begin
    case (bits)
      4'b0000: allow_r = 1'b1;
      4'b0001: allow_r = 1'b1;
      4'b0010: allow_r = 1'b1;
      4'b0011: allow_r = 1'b1;
      4'b0100: allow_r = 1'b1;
      4'b0101: allow_r = 1'b1;
      4'b0110: allow_r = 1'b1;
      4'b0111: allow_r = 1'b0;
      4'b1000: allow_r = 1'b1;
      4'b1001: allow_r = 1'b0;
      4'b1010: allow_r = 1'b1;
      4'b1011: allow_r = 1'b0;
      4'b1100: allow_r = 1'b1;
      4'b1101: allow_r = 1'b0;
      4'b1110: allow_r = 1'b1;
      4'b1111: allow_r = 1'b0;
      default: allow_r = 1'b0;
    endcase
  end
endmodule
