// =============================================================================
// Auto-generated by wca_lut_edge.fpga.ph_energy_burn — DO NOT EDIT BY HAND
// Software reference only — NO board synthesis / place-and-route claimed.
//
// Port-Hamiltonian pendulum energy certificate (fixed-point)
//   V    = 0.5 * (g * theta^2 + omega^2)     // 1/2 x^T M x, M=diag(g,1)
//   Vdot = omega * u                         // structural: grad(V)^T G u
//   energy_ok <=> (Vdot_q <= eps_q)
//
// Integer twin of FixedPointPHCertificate:
//   V_num  = (((g_q * theta_q^2) >>> FRAC) + omega_q^2) >>> 1
//   Vdot_q = (omega_q * u_q) >>> FRAC
//
// Q-format: signed Q8.8  (width=16, frac=8)
//   g_q=2511  (g=9.81)
//   eps_q=13  (vdot_eps=0.05)
//   v_max_q=None
//   lsb_tolerance=0 (bit-exact vs Python golden)
// =============================================================================
module wca_ph_energy (
  input  wire signed [15:0] theta_q,
  input  wire signed [15:0] omega_q,
  input  wire signed [15:0] u_q,
  output wire                      energy_ok,
  output wire signed [39:0] V_num,
  output wire signed [31:0] Vdot_q
);
  localparam integer FRAC = 8;
  localparam signed [15:0] G_Q   = 16'sd2511;
  localparam signed [31:0] EPS_Q = 32'sd13;

  // 64-bit signed intermediates — same truncation order as Python ints → assign
  reg signed [63:0] t2;
  reg signed [63:0] w2;
  reg signed [63:0] g_t2;
  reg signed [63:0] v_sum;
  reg signed [63:0] wu;
  reg signed [39:0] V_num_r;
  reg signed [31:0] Vdot_r;
  reg energy_ok_r;

  always @(*) begin
    t2    = $signed(theta_q) * $signed(theta_q);
    w2    = $signed(omega_q) * $signed(omega_q);
    g_t2  = $signed(G_Q) * t2;
    v_sum = (g_t2 >>> FRAC) + w2;
    V_num_r = v_sum >>> 1;
    wu      = $signed(omega_q) * $signed(u_q);
    Vdot_r  = wu >>> FRAC;
    if (Vdot_r <= EPS_Q)
      energy_ok_r = 1'b1;
    else
      energy_ok_r = 1'b0;
  end

  assign V_num     = V_num_r;
  assign Vdot_q    = Vdot_r;
  assign energy_ok = energy_ok_r;
endmodule
