# Alchitry Pt V2 — Klere die + UART bridge (FT2232H channel B)
set_property LOC W19 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -name clk -period 10.000 [get_ports clk]
set_property LOC AA20 [get_ports usb_rx]
set_property IOSTANDARD LVCMOS33 [get_ports usb_rx]
set_property LOC AA21 [get_ports usb_tx]
set_property IOSTANDARD LVCMOS33 [get_ports usb_tx]
set_property LOC P19 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property LOC P20 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property LOC T21 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property LOC R19 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property LOC V22 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property LOC U21 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property LOC T20 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property LOC W20 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
