// Generated by openie-fpga v0.1.0
// Graph: wca_commit_gate_pt_v2
// Target: 100 MHz
// Resources: ~1344 LUTs, ~960 FFs, ~0 DSPs, ~0 BRAMs

module wca_commit_gate_pt_v2 (
    input  wire clk,
    input  wire rst_n,
    input  wire        clk,
    input  wire [ 63:0] counter,
    output wire [ 63:0] led0,
    output wire [ 63:0] led1,
    output wire [ 63:0] led2,
    output wire [ 63:0] led3,
    output wire [ 63:0] led7
);

    // ── Internal signals ──
    wire [ 63:0] n4; // next_count
    wire [ 63:0] n5; // counter
    wire [ 63:0] n7; // energy_bits
    wire [ 63:0] n8; // energy_z
    wire [ 63:0] n9; // energy_ok
    wire [ 63:0] n11; // lut_bits
    wire [ 63:0] n12; // lut_allow
    wire [ 63:0] n13; // commit
    wire [ 63:0] n14; // refuse
    wire [ 63:0] n16; // heartbeat

    // ── Dataflow logic ──
    assign n15 = 24'h0000000000800000;
    assign n10 = 24'h0000000000000004;
    assign n6 = 24'h0000000000100000;
    assign n2 = 24'h0000000000000000;
    assign n1 = 24'h0000000000000001;
    assign n4 = counter + n1;
    reg [ 63:0] n5_reg;
    always @(posedge clk)
        if (!rst_n) n5_reg <= 0;
        else n5_reg <= n4;
    assign n5 = n5_reg;
    assign n16 = n5 & n15;
    assign n11 = n5 & n10;
    assign n12 = (n11 == n2);
    assign n7 = n5 & n6;
    assign n8 = (n7 == n2);
    assign n9 = ~n8;
    assign n13 = n12 & n9;
    assign n14 = ~n13;

    // ── Output assignments ──
    assign led0 = n13;
    assign led1 = n14;
    assign led2 = n12;
    assign led3 = n9;
    assign led7 = n16;

endmodule
