// =============================================================================
// Auto-generated by wca_commit::burn — Safe Q16.16 Ames energy-set CBF
// Software reference / Stage C fabric twin — energy UNMETERED on board.
//
// Float: h = E_max - V, V = 1/2 (g θ² + ω²); allow ⇔ h≥0 ∧ ω·u ≤ κ·h
// Integer (never false-allow; soft-mul only, no dividers):
//   cbf_ok <=> h_num ≥ 0 && (lhs * S) ≤ (4 * κ_q * h_num)
//   lhs = 4*om*u + 2*(|om|+|u|) + 1
//   h_num = e_max_num - V_ceil   (V_ceil via shift+sticky)
//   FRAC=16, S=65536, E_max=18, κ=0.05
//   e_max_num=77309411328, κ_q=3276, g_q=642908
// =============================================================================
module wca_cbf_energy (
  input  wire signed [31:0] theta_q,
  input  wire signed [31:0] omega_q,
  input  wire signed [31:0] u_q,
  output wire                      cbf_ok,
  output wire signed [127:0]       h_num,
  output wire signed [127:0]       lhs
);
  localparam integer FRAC = 16;
  localparam signed [31:0] G_Q = 32'sd642908;
  localparam signed [127:0] E_MAX_NUM = 128'sd77309411328;
  localparam signed [127:0] KAPPA_Q = 128'sd3276;
  localparam signed [127:0] S = 128'sd65536;

  reg signed [127:0] t2, w2, g_t2, g_t2_ceil, v_sum, v_ceil;
  reg signed [127:0] h_r, prod, abs_om, abs_u, abs_sum, lhs_r, lhs_s, rhs_x;
  reg cbf_ok_r;
  reg sticky;

  always @(*) begin
    t2   = $signed(theta_q) * $signed(theta_q);
    w2   = $signed(omega_q) * $signed(omega_q);
    g_t2 = $signed(G_Q) * t2;
    // ceil(g_t2 / S) via floor>> + sticky (no divider)
    sticky = |g_t2[FRAC-1:0];
    g_t2_ceil = (g_t2 >>> FRAC) + (sticky ? 128'sd1 : 128'sd0);
    v_sum = g_t2_ceil + w2;
    // ceil(v_sum / 2)
    v_ceil = (v_sum >>> 1) + {127'b0, v_sum[0]};
    h_r = E_MAX_NUM - v_ceil;

    prod = $signed(omega_q) * $signed(u_q);
    abs_om = (omega_q[31]) ? -$signed(omega_q) : $signed(omega_q);
    abs_u  = (u_q[31]) ? -$signed(u_q) : $signed(u_q);
    abs_sum = abs_om + abs_u;
    lhs_r = (prod * 128'sd4) + (abs_sum * 128'sd2) + 128'sd1;

    // Cross-multiply: lhs * S <= 4 * κ_q * h_num
    lhs_s = lhs_r * S;
    rhs_x = 128'sd4 * KAPPA_Q * h_r;
    if (h_r < 0)
      cbf_ok_r = 1'b0;
    else
      cbf_ok_r = (lhs_s <= rhs_x);
  end

  assign h_num  = h_r;
  assign lhs    = lhs_r;
  assign cbf_ok = cbf_ok_r;
endmodule
